### ISSUE TITLE
Security certificate expired 

### ISSUE THREAD

**Issue by bdobby** [plate0/platezero#423]

**Comment by ethanmick** [comment]
Resolved, sorry about that!

**Comment by bdobby** [comment]
no problem. Hope you enjoyed Thanksgiving.
Peace & Love
    Brian

Brian Dobby

My mailbox is protected and cleaned by cleanfox.io
<https://chrome.google.com/webstore/detail/cleanfox/fpejofmgechlgfomhbgjglkboeoobnma>


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
